"""add authentication fields to users

Revision ID: 92729f84240a
Revises: cff4dc36cc7a
Create Date: 2026-09-23 04:52:33.906923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92729f84240a'
down_revision: Union[str, Sequence[str], None] = 'cff4dc36cc7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Se agrega con un valor temporal (server_default) para no romper filas
    # existentes; luego se retira el default para que la app siempre exija
    # un hash real al crear usuarios nuevos.
    op.add_column(
        'users',
        sa.Column(
            'hashed_password',
            sa.String(length=255),
            nullable=False,
            server_default='__MIGRATED_WITHOUT_PASSWORD__',
        ),
    )
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('hashed_password', server_default=None)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
